//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElicBibl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Book
    {
        public int id { get; set; }
        public string Name { get; set; }
        public string Author { get; set; }
        public string NumberBook { get; set; }
        public string Summary { get; set; }
    }
}
